name: Sample workflow for trial

on:
  schedule:
  - cron: "15 7 * * 1-5"
  
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:

  build-dotnet:

    runs-on: ubuntu-latest

    env:
      solution: Everythinhg.sln

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      
      

    
    
  
